version: '3'
services:
  server:
    build:
      context: .
    ports:
      - 8010:8000
    volumes:
      - /mnt/c/Sandboxes:/mnt/c/Sandboxes
      - ./testdir:/app/testdir
      - ./src/docs/ignore.md:/app/src/docs/ignore.md
      - ./src/db:/app/src/db  # Persist the database between container restarts
    environment:
      - API_HOST=localhost
      - API_PORT=8010
      - CACHE_SIZE_MB=100
      - THREAD_POOL_SIZE=10
    restart: unless-stopped