#!/usr/bin/env python3
"""
Script to set the API host and port by creating or modifying the .env file.
This provides an easy way to configure the application's API URL.
"""
import os
import sys
import argparse

def main():
    parser = argparse.ArgumentParser(description="Set API URL configuration")
    parser.add_argument("--host", default="localhost", help="API host to use")
    parser.add_argument("--port", type=int, default=8010, help="API port to use")
    args = parser.parse_args()
    
    # Get project root directory (the directory containing this script)
    project_root = os.path.dirname(os.path.abspath(__file__))
    env_file = os.path.join(project_root, ".env")
    
    # Read existing .env file if it exists
    env_vars = {}
    if os.path.exists(env_file):
        with open(env_file, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_vars[key.strip()] = value.strip()
    
    # Update API_HOST and API_PORT
    env_vars["API_HOST"] = args.host
    env_vars["API_PORT"] = str(args.port)
    
    # Write the updated .env file
    with open(env_file, "w") as f:
        f.write("# Filesystem API Configuration\n")
        f.write("# Generated by set_api_url.py\n\n")
        
        for key, value in sorted(env_vars.items()):
            f.write(f"{key}={value}\n")
    
    print(f"API URL configuration updated: http://{args.host}:{args.port}")
    print(f"Configuration saved to: {env_file}")
    
if __name__ == "__main__":
    main()